apiVersion: batch/v1
kind: CronJob
metadata:
  name: ml-modelling
  namespace: car-classification
spec:
  jobTemplate:
    metadata:
      name: ml-modelling
    spec:
      template:
        spec:
          containers:
            - image: justingodden/car-classification-ml-modelling:0.2.2
              name: ml-modelling
              env:
                - name: S3_BUCKET_NAME
                  value: arena-car-classification-training-images
              resources:
                requests:
                  cpu: "1"
                  memory: 4Gi
          restartPolicy: OnFailure
  schedule: 0 0 0 * *
